"""
Part 2: BOP Dataset Visualisation Dashboard
============================================
Visualises ground truth vs predicted poses, 2D bounding boxes, binary masks,
and per-frame error metrics from the TUD-L sub-dataset of BOP.

Uses dummy (mock) predictions generated by perturbing ground truth,
since we don't have a real prediction model yet.

Features:
- 2D view: RGB image with GT/Pred bounding boxes + binary mask overlays
- 3D view: 3D coordinate frames for GT (green) vs Pred (red) poses
- Error graphs: rotation error, translation error, mask IOU — all updating per frame
- Frame switching: slider + left/right arrow keys
- Toggle checkboxes for GT/Pred visibility

Author: Built on Viser (viser) for the interactive web dashboard.
"""

import json
import os
import time
from typing import Optional, Dict

import numpy as np
import cv2
from PIL import Image, ImageDraw
import plotly.graph_objects as go
import trimesh
import viser
import viser.transforms as tf

# =============================================================================
# CONFIGURATION
# =============================================================================
DATA_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../data/000001"))
RGB_DIR = os.path.join(DATA_DIR, "rgb")
MASK_DIR = os.path.join(DATA_DIR, "mask")
MASK_VISIB_DIR = os.path.join(DATA_DIR, "mask_visib")

# Path to the 3D CAD models (.ply files) for TUD-L objects
MODEL_DIR = "/home/aryan/Downloads/tudl_models/models"

# Colours (RGBA)
COLOR_GT = (0, 255, 0, 200)       # green for ground truth
COLOR_PRED = (255, 60, 60, 200)    # red for predictions

# =============================================================================
# MATH HELPERS
# =============================================================================
def rotation_error_deg(R_gt: np.ndarray, R_pred: np.ndarray) -> float:
    """Angular distance between two 3x3 rotation matrices, in degrees.
    
    Formula: θ = arccos((trace(R_gt^T * R_pred) - 1) / 2)
    This comes from the axis-angle representation: for any rotation matrix R,
    trace(R) = 1 + 2·cos(θ). Applying this to the difference rotation R_diff
    = R_gt^T · R_pred gives the net rotation angle between them.
    """
    R_diff = R_gt.T @ R_pred
    trace = np.trace(R_diff)
    cos_theta = np.clip((trace - 1.0) / 2.0, -1.0, 1.0)
    return float(np.degrees(np.arccos(cos_theta)))


def translation_error_mm(t_gt: np.ndarray, t_pred: np.ndarray) -> float:
    """Euclidean distance between two translation vectors, in mm."""
    return float(np.linalg.norm(t_gt - t_pred))


def compute_iou(mask_a: np.ndarray, mask_b: np.ndarray) -> float:
    """Intersection-over-Union for two binary masks.
    
    IOU = |A ∩ B| / |A ∪ B|, where |·| counts non-zero pixels.
    Range: [0, 1].  1.0 = perfect overlap, 0.0 = no overlap.
    """
    intersection = np.logical_and(mask_a, mask_b).sum()
    union = np.logical_or(mask_a, mask_b).sum()
    if union == 0:
        return 1.0  # both empty → perfect agreement
    return float(intersection / union)


def matrix_to_quat_wxyz(R: np.ndarray) -> np.ndarray:
    """Convert 3x3 rotation matrix to wxyz quaternion (Viser convention)."""
    return tf.SO3.from_matrix(R).wxyz

# =============================================================================
# MESH CACHE — load 3D CAD models once, reuse across frames
# =============================================================================
_mesh_cache: Dict[int, trimesh.Trimesh] = {}

def get_mesh(obj_id: int) -> Optional[trimesh.Trimesh]:
    """Load a .ply CAD model for a given object ID. Cached after first load."""
    if obj_id in _mesh_cache:
        return _mesh_cache[obj_id]
    ply_path = os.path.join(MODEL_DIR, f"obj_{obj_id:06d}.ply")
    if not os.path.exists(ply_path):
        print(f"Warning: mesh not found at {ply_path}")
        _mesh_cache[obj_id] = None
        return None
    mesh = trimesh.load(ply_path)
    _mesh_cache[obj_id] = mesh
    print(f"Loaded mesh for obj_{obj_id:06d}: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")
    return mesh


# =============================================================================
# DATA LOADING
# =============================================================================
def load_json(filename: str) -> dict:
    filepath = os.path.join(DATA_DIR, filename)
    with open(filepath, "r") as f:
        return json.load(f)


def load_mask(frame_id: int, obj_seq: int = 0) -> Optional[np.ndarray]:
    """Load the full (amodal) binary mask for a given frame+object.
    
    BOP mask naming: {frame_id:05d}_{obj_seq:06d}.png
    where obj_seq is the 0-based index of the object within the scene,
    NOT the obj_id from scene_gt.json.
    """
    fname = f"{frame_id:06d}_{obj_seq:06d}.png"
    fpath = os.path.join(MASK_DIR, fname)
    if not os.path.exists(fpath):
        return None
    img = cv2.imread(fpath, cv2.IMREAD_GRAYSCALE)
    return (img > 0).astype(np.uint8)


def load_mask_visib(frame_id: int, obj_seq: int = 0) -> Optional[np.ndarray]:
    """Load the visible-part binary mask for a given frame+object.
    
    BOP mask naming: {frame_id:06d}_{obj_seq:06d}.png
    """
    fname = f"{frame_id:06d}_{obj_seq:06d}.png"
    fpath = os.path.join(MASK_VISIB_DIR, fname)
    if not os.path.exists(fpath):
        return None
    img = cv2.imread(fpath, cv2.IMREAD_GRAYSCALE)
    return (img > 0).astype(np.uint8)


# =============================================================================
# MOCK PREDICTION GENERATION
# =============================================================================
def generate_mock_predictions(scene_gt: dict) -> dict:
    """Create dummy predictions by perturbing ground truth poses."""
    predictions = {}
    for f_str, objs in scene_gt.items():
        predictions[f_str] = []
        for obj in objs:
            R_gt = np.array(obj["cam_R_m2c"]).reshape(3, 3)
            t_gt = np.array(obj["cam_t_m2c"])

            # Perturb translation: Gaussian noise σ=15 mm
            t_noise = np.random.normal(0, 15, 3)
            t_pred = t_gt + t_noise

            # Perturb rotation: random axis, small angle ~5-10°
            axis = np.random.randn(3)
            axis /= np.linalg.norm(axis)
            angle_rad = np.random.uniform(0.05, 0.18)  # ~3° to 10°
            # Rodrigues rotation formula via skew-symmetric matrix K
            K = np.array([
                [0, -axis[2], axis[1]],
                [axis[2], 0, -axis[0]],
                [-axis[1], axis[0], 0],
            ])
            R_noise = np.eye(3) + np.sin(angle_rad) * K + (1 - np.cos(angle_rad)) * (K @ K)
            R_pred = R_noise @ R_gt

            predictions[f_str].append({
                "obj_id": obj["obj_id"],
                "cam_t_m2c": t_pred.tolist(),
                "cam_R_m2c": R_pred.flatten().tolist(),
            })
    return predictions


def generate_mock_mask_prediction(gt_mask: np.ndarray, frame_id: int, obj_id: int) -> np.ndarray:
    """Simulate a predicted mask by eroding/dilating the GT mask.
    
    Uses deterministic pseudo-randomness seeded by frame+obj so the same
    (frame, obj) always produces the same 'prediction'.
    """
    if gt_mask is None or gt_mask.sum() == 0:
        return np.zeros((480, 640), dtype=np.uint8)

    rng = np.random.RandomState(frame_id * 1000 + obj_id)
    kernel_size = rng.randint(1, 8)  # erosion kernel 1..7 px
    kernel = np.ones((kernel_size, kernel_size), np.uint8)

    if rng.rand() > 0.5:
        pred = cv2.erode(gt_mask, kernel, iterations=1)
    else:
        pred = cv2.dilate(gt_mask, kernel, iterations=1)

    # Add occasional random shift (0-3 px)
    shift = rng.randint(0, 4)
    if shift > 0:
        dx, dy = rng.randint(-shift, shift + 1, 2)
        M = np.float32([[1, 0, dx], [0, 1, dy]])
        pred = cv2.warpAffine(pred, M, (pred.shape[1], pred.shape[0]))

    return pred


# =============================================================================
# 2D RENDERING: draw bounding boxes & masks onto the RGB image
# =============================================================================
def render_2d_composite(
    frame_id: int,
    scene_gt: dict,
    scene_gt_info: dict,
    predictions: dict,
    show_gt: bool,
    show_pred: bool,
) -> np.ndarray:
    """Return an RGBA numpy array of the RGB image with GT/Pred overlays drawn."""
    rgb_path = os.path.join(RGB_DIR, f"{frame_id:06d}.png")
    if not os.path.exists(rgb_path):
        return np.zeros((480, 640, 4), dtype=np.uint8)

    img = cv2.imread(rgb_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    # Convert to RGBA PIL image for alpha-composited drawing
    pil_img = Image.fromarray(img).convert("RGBA")
    overlay = Image.new("RGBA", pil_img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    f_str = str(frame_id)

    def draw_bbox(draw_obj, bbox, colour, label: str):
        """bbox format: [x, y, w, h] (BOP convention)."""
        x, y, w, h = bbox
        r, g, b, a = colour
        # Rectangle outline
        draw_obj.rectangle([x, y, x + w, y + h], outline=(r, g, b, a), width=2)
        # Label text
        tx, ty = x, max(y - 14, 0)
        draw_obj.rectangle([tx, ty, tx + 70, ty + 14], fill=(r, g, b, 180))
        draw_obj.text((tx + 2, ty), label, fill=(255, 255, 255, 255))

    if f_str in scene_gt:
        for obj_idx, gt_obj in enumerate(scene_gt[f_str]):
            gt_info_list = scene_gt_info.get(f_str, [])
            if obj_idx < len(gt_info_list):
                info = gt_info_list[obj_idx]
                if show_gt:
                    draw_bbox(draw, info["bbox_obj"], COLOR_GT, f"GT obj{gt_obj['obj_id']}")
                if show_pred and f_str in predictions and obj_idx < len(predictions[f_str]):
                    # Perturb the bbox to simulate prediction error
                    bx, by, bw, bh = info["bbox_obj"]
                    rng = np.random.RandomState(frame_id * 1000 + obj_idx)
                    bx += rng.randint(-12, 12)
                    by += rng.randint(-12, 12)
                    bw += rng.randint(-8, 8)
                    bh += rng.randint(-8, 8)
                    bw = max(5, bw)
                    bh = max(5, bh)
                    pred_bbox = [max(0, bx), max(0, by), bw, bh]
                    draw_bbox(draw, pred_bbox, COLOR_PRED, f"Pred obj{gt_obj['obj_id']}")

    # Draw mask overlays
    if f_str in scene_gt:
        for obj_idx, gt_obj in enumerate(scene_gt[f_str]):
            obj_id = gt_obj["obj_id"]
            gt_mask = load_mask(frame_id, obj_idx)
            pred_mask = None
            if gt_mask is not None:
                pred_mask = generate_mock_mask_prediction(gt_mask, frame_id, obj_id)

            if show_gt and gt_mask is not None:
                mask_colour = (0, 255, 0, 60)  # semi-transparent green
                mask_rgba = np.zeros((gt_mask.shape[0], gt_mask.shape[1], 4), dtype=np.uint8)
                mask_rgba[gt_mask > 0] = mask_colour
                mask_pil = Image.fromarray(mask_rgba, "RGBA")
                overlay = Image.alpha_composite(overlay, mask_pil)

            if show_pred and pred_mask is not None:
                mask_colour = (255, 60, 60, 60)  # semi-transparent red
                mask_rgba = np.zeros((pred_mask.shape[0], pred_mask.shape[1], 4), dtype=np.uint8)
                mask_rgba[pred_mask > 0] = mask_colour
                mask_pil = Image.fromarray(mask_rgba, "RGBA")
                overlay = Image.alpha_composite(overlay, mask_pil)

            draw = ImageDraw.Draw(overlay)  # reacquire after composite

    result = Image.alpha_composite(pil_img, overlay)
    return np.array(result)


# =============================================================================
# INTERACTIVE PLOTLY ERROR GRAPHS
# =============================================================================
def build_error_plotly(
    frame_ids: list,
    scene_gt: dict,
    predictions: dict,
    current_frame: Optional[int] = None,
) -> go.Figure:
    """Build a 3-panel Plotly subplot with hover tooltips: rotation error,
    translation error, and mask IOU.  Hovering any data point shows the
    exact frame number and error value.
    """
    # Accumulate per-object errors
    rot_errors = []   # (frame, error, obj_id)
    trans_errors = [] # (frame, error, obj_id)
    iou_errors = []   # (frame, 1-IOU, obj_id)

    for f_id in frame_ids:
        f_str = str(f_id)
        if f_str not in scene_gt or f_str not in predictions:
            continue
        for obj_idx, (gt_obj, pred_obj) in enumerate(zip(scene_gt[f_str], predictions[f_str])):
            R_gt = np.array(gt_obj["cam_R_m2c"]).reshape(3, 3)
            t_gt = np.array(gt_obj["cam_t_m2c"])
            R_pred = np.array(pred_obj["cam_R_m2c"]).reshape(3, 3)
            t_pred = np.array(pred_obj["cam_t_m2c"])
            obj_id = gt_obj["obj_id"]

            rot_errors.append((f_id, rotation_error_deg(R_gt, R_pred), obj_id))
            trans_errors.append((f_id, translation_error_mm(t_gt, t_pred), obj_id))

            gt_mask = load_mask(f_id, obj_idx)
            pred_mask = generate_mock_mask_prediction(
                gt_mask if gt_mask is not None else np.zeros((480, 640), dtype=np.uint8),
                f_id, obj_id,
            )
            if gt_mask is not None:
                iou = compute_iou(gt_mask, pred_mask)
                iou_errors.append((f_id, 1.0 - iou, obj_id))

    def _unpack(data):
        if not data:
            return [], [], []
        xs, ys, ids = zip(*data)
        return list(xs), list(ys), list(ids)

    xs_rot, ys_rot, ids_rot = _unpack(rot_errors)
    xs_trans, ys_trans, ids_trans = _unpack(trans_errors)
    xs_iou, ys_iou, ids_iou = _unpack(iou_errors)

    fig = go.Figure()

    # Panel 1: Rotation Error
    fig.add_trace(go.Scatter(
        x=xs_rot, y=ys_rot, mode="markers+lines",
        marker=dict(size=4, color="#ff9944"), line=dict(width=1, color="#ff9944"),
        name="Rot Err (deg)",
        customdata=list(zip(ids_rot)),
        hovertemplate="Frame %{x}<br>Rot Err: %{y:.2f}°<br>Obj %{customdata[0]}<extra></extra>",
        yaxis="y1",
    ))

    # Panel 2: Translation Error
    fig.add_trace(go.Scatter(
        x=xs_trans, y=ys_trans, mode="markers+lines",
        marker=dict(size=4, color="#44aaff"), line=dict(width=1, color="#44aaff"),
        name="Trans Err (mm)",
        customdata=list(zip(ids_trans)),
        hovertemplate="Frame %{x}<br>Trans Err: %{y:.2f} mm<br>Obj %{customdata[0]}<extra></extra>",
        yaxis="y2",
    ))

    # Panel 3: Mask Error (1 - IOU)
    fig.add_trace(go.Scatter(
        x=xs_iou, y=ys_iou, mode="markers+lines",
        marker=dict(size=4, color="#44ff88"), line=dict(width=1, color="#44ff88"),
        name="Mask Err (1-IOU)",
        customdata=list(zip(ids_iou)),
        hovertemplate="Frame %{x}<br>Mask Err: %{y:.4f}<br>Obj %{customdata[0]}<extra></extra>",
        yaxis="y3",
    ))

    # Current-frame vertical line annotations across all subplots
    shapes = []
    if current_frame is not None:
        shapes.append(dict(
            type="line", x0=current_frame, x1=current_frame,
            y0=0, y1=1, yref="paper",
            line=dict(color="#ffdd00", width=1.5, dash="dash"),
        ))

    # Layout: 3 rows, 1 column, shared x-axis
    fig.update_layout(
        template="plotly_dark",
        height=600,
        margin=dict(l=50, r=20, t=40, b=40),
        hovermode="x unified",
        shapes=shapes,
        grid=dict(rows=3, columns=1, pattern="independent"),
        xaxis3=dict(title="Frame ID"),
        yaxis1=dict(title="Degrees", domain=[0.68, 1.0]),
        yaxis2=dict(title="mm", domain=[0.35, 0.65]),
        yaxis3=dict(title="1 - IOU", domain=[0.0, 0.32]),
    )

    return fig


# =============================================================================
# MAIN DASHBOARD
# =============================================================================
def main():
    print("═" * 60)
    print("  BOP Dataset Visualisation Dashboard — Part 2")
    print("  Dataset: TUD-L  |  Scene: 000001")
    print("═" * 60)

    # --- Load data ---
    scene_camera = load_json("scene_camera.json")
    scene_gt = load_json("scene_gt.json")
    scene_gt_info = load_json("scene_gt_info.json")

    frame_ids = sorted(int(k) for k in scene_camera.keys())
    min_frame, max_frame = frame_ids[0], frame_ids[-1]
    print(f"Loaded {len(frame_ids)} frames (IDs {min_frame}..{max_frame})")

    # --- Generate mock predictions ---
    print("Generating mock predictions (pose + mask)...")
    predictions = generate_mock_predictions(scene_gt)

    # Preload all mask IOU data for the global error graph
    print("Computing mask IOUs for all frames...")
    all_mask_ious = {}
    for f_id in frame_ids:
        f_str = str(f_id)
        if f_str in scene_gt:
            for obj_idx, obj in enumerate(scene_gt[f_str]):
                gt_mask = load_mask(f_id, obj_idx)
                pred_mask = generate_mock_mask_prediction(
                    gt_mask if gt_mask is not None else np.zeros((480, 640), dtype=np.uint8),
                    f_id,
                    obj["obj_id"],
                )
                if gt_mask is not None:
                    all_mask_ious[(f_id, obj["obj_id"])] = compute_iou(gt_mask, pred_mask)

    # --- Start Viser server ---
    server = viser.ViserServer()
    print("\nViser server started → http://localhost:8080\n")

    # Pre-render the Plotly error graph
    error_plotly_fig = build_error_plotly(frame_ids, scene_gt, predictions)

    # --- GUI: left panel controls ---
    with server.gui.add_folder("🎮 Controls"):
        frame_slider = server.gui.add_slider(
            "Frame",
            min=min_frame,
            max=max_frame,
            step=1,
            initial_value=min_frame,
        )
        btn_prev = server.gui.add_button("◀ Prev Frame")
        btn_next = server.gui.add_button("Next Frame ▶")
        show_gt_cb = server.gui.add_checkbox("Show Ground Truth", initial_value=True)
        show_pred_cb = server.gui.add_checkbox("Show Predictions", initial_value=True)
        stats_md = server.gui.add_markdown("*Use the slider or Prev/Next buttons to switch frames*")

    # The 2D composite image (rendered each frame change)
    with server.gui.add_folder("📷 2D View (RGB + Boxes + Masks)"):
        composite_2d = render_2d_composite(min_frame, scene_gt, scene_gt_info, predictions, True, True)
        image_gui = server.gui.add_image(
            composite_2d,
            format="png",
        )

    # Error graph panel — interactive Plotly with hover tooltips
    with server.gui.add_folder("📈 Error Graphs"):
        graph_gui = server.gui.add_plotly(
            error_plotly_fig,
            config={"displayModeBar": True, "displaylogo": False},
        )

    # 3D scene setup
    server.scene.add_icosphere(
        "/origin",
        radius=8.0,
        position=(0, 0, 0),
        color=(150, 150, 150),
    )

    # Store handles for 3D scene objects so we can clear them
    scene_handles = []

    # Preload all CAD meshes referenced in the dataset at startup
    print("Loading 3D CAD models...")
    all_obj_ids = set()
    for f_str in scene_gt:
        for obj in scene_gt[f_str]:
            all_obj_ids.add(obj["obj_id"])
    for oid in sorted(all_obj_ids):
        get_mesh(oid)  # triggers cache loading
    print(f"Cached {len(_mesh_cache)} meshes.\n")

    def draw_3d_objects(frame_id: int):
        """Draw/update 3D CAD meshes at GT (green) and Pred (red) poses."""
        nonlocal scene_handles
        for h in scene_handles:
            h.remove()
        scene_handles.clear()

        f_str = str(frame_id)
        if f_str not in scene_gt:
            return

        # Camera at origin with coordinate axes
        cam_handle = server.scene.add_frame(
            "/camera_origin",
            show_axes=True,
            axes_length=50.0,
            axes_radius=3.0,
            position=(0, 0, 0),
        )
        scene_handles.append(cam_handle)

        for obj_idx, gt_obj in enumerate(scene_gt[f_str]):
            obj_id = gt_obj["obj_id"]
            mesh = _mesh_cache.get(obj_id)

            # ---- GROUND TRUTH (solid green) ----
            if show_gt_cb.value:
                R_gt = np.array(gt_obj["cam_R_m2c"]).reshape(3, 3)
                t_gt = np.array(gt_obj["cam_t_m2c"])
                wxyz_gt = matrix_to_quat_wxyz(R_gt)

                if mesh is not None:
                    # Render the CAD model as a solid green mesh
                    h_mesh = server.scene.add_mesh_simple(
                        f"/gt_mesh_{obj_id}",
                        vertices=np.asarray(mesh.vertices, dtype=np.float32),
                        faces=np.asarray(mesh.faces, dtype=np.uint32),
                        color=(0, 180, 0),        # solid green fill
                        wireframe=False,
                        flat_shading=False,
                        position=t_gt,
                        wxyz=wxyz_gt,
                    )
                    scene_handles.append(h_mesh)
                else:
                    h_box = server.scene.add_box(
                        f"/gt_box_{obj_id}",
                        dimensions=(30, 30, 30),
                        position=t_gt,
                        wxyz=wxyz_gt,
                        color=(0, 200, 0),
                    )
                    scene_handles.append(h_box)
                # Coordinate frame for orientation reference
                h_frame = server.scene.add_frame(
                    f"/gt_frame_{obj_id}",
                    show_axes=True,
                    axes_length=30.0,
                    axes_radius=1.5,
                    position=t_gt,
                    wxyz=wxyz_gt,
                )
                scene_handles.append(h_frame)

            # ---- PREDICTION (solid red) ----
            if show_pred_cb.value and f_str in predictions and obj_idx < len(predictions[f_str]):
                pred_obj = predictions[f_str][obj_idx]
                R_pred = np.array(pred_obj["cam_R_m2c"]).reshape(3, 3)
                t_pred = np.array(pred_obj["cam_t_m2c"])
                wxyz_pred = matrix_to_quat_wxyz(R_pred)

                if mesh is not None:
                    # Same CAD model, placed at the predicted pose — solid red
                    h_mesh = server.scene.add_mesh_simple(
                        f"/pred_mesh_{obj_id}",
                        vertices=np.asarray(mesh.vertices, dtype=np.float32),
                        faces=np.asarray(mesh.faces, dtype=np.uint32),
                        color=(180, 20, 20),      # solid red fill
                        wireframe=False,
                        flat_shading=False,
                        position=t_pred,
                        wxyz=wxyz_pred,
                    )
                    scene_handles.append(h_mesh)
                else:
                    h_box = server.scene.add_box(
                        f"/pred_box_{obj_id}",
                        dimensions=(30, 30, 30),
                        position=t_pred,
                        wxyz=wxyz_pred,
                        color=(200, 40, 40),
                    )
                    scene_handles.append(h_box)
                h_frame = server.scene.add_frame(
                    f"/pred_frame_{obj_id}",
                    show_axes=True,
                    axes_length=30.0,
                    axes_radius=1.5,
                    position=t_pred,
                    wxyz=wxyz_pred,
                )
                scene_handles.append(h_frame)

    def update_all(frame_id: int):
        """Refresh 2D composite, 3D scene, error graph, and stats text."""
        # 2D composite
        comp = render_2d_composite(
            frame_id, scene_gt, scene_gt_info, predictions,
            show_gt_cb.value, show_pred_cb.value,
        )
        image_gui.image = comp

        # 3D scene
        draw_3d_objects(frame_id)

        # Error graph (redraw Plotly with current-frame marker)
        eg = build_error_plotly(frame_ids, scene_gt, predictions, frame_id)
        graph_gui.figure = eg

        # Stats markdown
        f_str = str(frame_id)
        md = f"### Frame {frame_id}\n"
        if f_str in scene_gt and f_str in predictions:
            for obj_idx, (gt_obj, pred_obj) in enumerate(zip(scene_gt[f_str], predictions[f_str])):
                R_gt = np.array(gt_obj["cam_R_m2c"]).reshape(3, 3)
                t_gt = np.array(gt_obj["cam_t_m2c"])
                R_pred = np.array(pred_obj["cam_R_m2c"]).reshape(3, 3)
                t_pred = np.array(pred_obj["cam_t_m2c"])
                obj_id = gt_obj["obj_id"]
                r_err = rotation_error_deg(R_gt, R_pred)
                t_err = translation_error_mm(t_gt, t_pred)
                iou_val = all_mask_ious.get((frame_id, obj_id), None)
                md += f"**Obj {obj_id}**\n"
                md += f"- Rot Err: `{r_err:.2f}°`\n"
                md += f"- Trans Err: `{t_err:.2f} mm`\n"
                if iou_val is not None:
                    md += f"- Mask IOU: `{iou_val:.4f}`\n"
                md += "\n"
        stats_md.content = md

    # --- Event callbacks ---
    @frame_slider.on_update
    def _(_):
        update_all(int(frame_slider.value))

    @btn_prev.on_click
    def _(_):
        new_val = max(min_frame, int(frame_slider.value) - 1)
        frame_slider.value = new_val

    @btn_next.on_click
    def _(_):
        new_val = min(max_frame, int(frame_slider.value) + 1)
        frame_slider.value = new_val

    @show_gt_cb.on_update
    def _(_):
        update_all(int(frame_slider.value))

    @show_pred_cb.on_update
    def _(_):
        update_all(int(frame_slider.value))

    # --- Initial draw ---
    update_all(min_frame)

    print("Dashboard ready! Use slider, buttons, or ← → arrow keys to navigate.\n")
    print("  Green  = Ground Truth     Red = Prediction\n")
    print("Press Ctrl+C to stop.")

    try:
        while True:
            time.sleep(0.5)
    except KeyboardInterrupt:
        print("\nShutting down.")


if __name__ == "__main__":
    main()