"""
Part 2: BOP Dataset Visualisation Dashboard
============================================
Visualises ground truth vs predicted poses, 2D bounding boxes, binary masks,
and per-frame error metrics from the TUD-L sub-dataset of BOP.

Uses dummy (mock) predictions generated by perturbing ground truth,
since we don't have a real prediction model yet.

Features:
- 2D view: RGB image with GT/Pred bounding boxes + binary mask overlays
- 3D view: 3D coordinate frames for GT (green) vs Pred (red) poses
- Error graphs: rotation error, translation error, mask IOU — all updating per frame
- Frame switching: slider + left/right arrow keys
- Toggle checkboxes for GT/Pred visibility

Author: Built on Viser (viser) for the interactive web dashboard.
"""

import json
import os
import time
import csv
import io
import zipfile
import tempfile
from typing import Optional, Dict
from concurrent.futures import ThreadPoolExecutor

import numpy as np
import cv2
from PIL import Image, ImageDraw
import plotly.graph_objects as go
import trimesh
import viser
import viser.transforms as tf

# =============================================================================
# CONFIGURATION
# =============================================================================
DATA_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../data/000001"))
RGB_DIR = os.path.join(DATA_DIR, "rgb")
MASK_DIR = os.path.join(DATA_DIR, "mask")
MASK_VISIB_DIR = os.path.join(DATA_DIR, "mask_visib")
_FRAME_PAD = 6  # default padding width; auto-detected from actual filenames

def _detect_frame_padding(mask_or_rgb_dir: str) -> int:
    """Look at filenames on disk to determine how many digits frame IDs use."""
    if not os.path.isdir(mask_or_rgb_dir):
        return 6
    for fname in os.listdir(mask_or_rgb_dir):
        # mask files: XXXXXX_XXXXXX.png, rgb files: XXXXXX.png
        name = fname.split("_")[0]
        name = name.split(".")[0]
        if name.isdigit():
            return len(name)
    return 6
_FRAME_PAD = _detect_frame_padding(MASK_DIR)

# Path to the 3D CAD models (.ply files) for TUD-L objects
MODEL_DIR = "/home/aryan/Downloads/tudl_models/models"

# Colours (RGBA)
COLOR_GT = (0, 255, 0, 200)       # green for ground truth
COLOR_PRED = (255, 60, 60, 200)    # red for predictions

# =============================================================================
# MATH HELPERS
# =============================================================================
def rotation_error_deg(R_gt: np.ndarray, R_pred: np.ndarray) -> float:
    """Angular distance between two 3x3 rotation matrices, in degrees.
    
    Formula: θ = arccos((trace(R_gt^T * R_pred) - 1) / 2)
    This comes from the axis-angle representation: for any rotation matrix R,
    trace(R) = 1 + 2·cos(θ). Applying this to the difference rotation R_diff
    = R_gt^T · R_pred gives the net rotation angle between them.
    """
    R_diff = R_gt.T @ R_pred
    trace = np.trace(R_diff)
    cos_theta = np.clip((trace - 1.0) / 2.0, -1.0, 1.0)
    return float(np.degrees(np.arccos(cos_theta)))


def translation_error_mm(t_gt: np.ndarray, t_pred: np.ndarray) -> float:
    """Euclidean distance between two translation vectors, in mm."""
    return float(np.linalg.norm(t_gt - t_pred))


def compute_iou(mask_a: np.ndarray, mask_b: np.ndarray) -> float:
    """Intersection-over-Union for two binary masks.
    
    IOU = |A ∩ B| / |A ∪ B|, where |·| counts non-zero pixels.
    Range: [0, 1].  1.0 = perfect overlap, 0.0 = no overlap.
    """
    intersection = np.logical_and(mask_a, mask_b).sum()
    union = np.logical_or(mask_a, mask_b).sum()
    if union == 0:
        return 1.0  # both empty → perfect agreement
    return float(intersection / union)


def matrix_to_quat_wxyz(R: np.ndarray) -> np.ndarray:
    """Convert 3x3 rotation matrix to wxyz quaternion (Viser convention)."""
    return tf.SO3.from_matrix(R).wxyz

# =============================================================================
# MESH CACHE — load 3D CAD models once, reuse across frames
# =============================================================================
_mesh_cache: Dict[int, trimesh.Trimesh] = {}

def get_mesh(obj_id: int) -> Optional[trimesh.Trimesh]:
    """Load a .ply CAD model for a given object ID. Cached after first load."""
    if obj_id in _mesh_cache:
        return _mesh_cache[obj_id]
    ply_path = os.path.join(MODEL_DIR, f"obj_{obj_id:06d}.ply")
    if not os.path.exists(ply_path):
        print(f"Warning: mesh not found at {ply_path}")
        _mesh_cache[obj_id] = None
        return None
    mesh = trimesh.load(ply_path)
    _mesh_cache[obj_id] = mesh
    print(f"Loaded mesh for obj_{obj_id:06d}: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")
    return mesh


# =============================================================================
# DATA LOADING
# =============================================================================
def load_json(filename: str) -> dict:
    filepath = os.path.join(DATA_DIR, filename)
    with open(filepath, "r") as f:
        return json.load(f)


def load_mask(frame_id: int, obj_seq: int = 0) -> Optional[np.ndarray]:
    """Load the full (amodal) binary mask for a given frame+object.
    
    BOP mask naming: {frame_id:0{FRAME_PAD}d}_{obj_seq:06d}.png
    where obj_seq is the 0-based index of the object within the scene,
    NOT the obj_id from scene_gt.json.
    """
    fname = f"{frame_id:0{_FRAME_PAD}d}_{obj_seq:06d}.png"
    fpath = os.path.join(MASK_DIR, fname)
    if not os.path.exists(fpath):
        return None
    img = cv2.imread(fpath, cv2.IMREAD_GRAYSCALE)
    return (img > 0).astype(np.uint8)


def load_mask_visib(frame_id: int, obj_seq: int = 0) -> Optional[np.ndarray]:
    """Load the visible-part binary mask for a given frame+object.
    
    BOP mask naming: {frame_id:0{FRAME_PAD}d}_{obj_seq:06d}.png
    """
    fname = f"{frame_id:0{_FRAME_PAD}d}_{obj_seq:06d}.png"
    fpath = os.path.join(MASK_VISIB_DIR, fname)
    if not os.path.exists(fpath):
        return None
    img = cv2.imread(fpath, cv2.IMREAD_GRAYSCALE)
    return (img > 0).astype(np.uint8)


# =============================================================================
# CSV PARSER — parse BOP-format prediction files uploaded by the user
# =============================================================================
def parse_bop_csv(csv_bytes: bytes) -> Dict[str, list]:
    """Parse a BOP-format CSV results file into our predictions dict.
    
    BOP CSV format (from https://bop.felk.cvut.cz/challenges/bop-challenge-2019/):
      scene_id, im_id, obj_id, score, R, t, time
    
    R is 9 space-separated floats (3×3 rotation matrix, row-major).
    t is 3 space-separated floats (translation vector in mm).
    
    Returns: dict mapping frame_id (str) → list of {obj_id, cam_R_m2c, cam_t_m2c}
    """
    text = csv_bytes.decode("utf-8")
    reader = csv.reader(io.StringIO(text))
    rows = list(reader)
    
    if len(rows) < 2:
        raise ValueError("CSV has no data rows (only header, or empty).")
    
    header = [h.strip().lower() for h in rows[0]]
    required = {"scene_id", "im_id", "obj_id", "r", "t"}
    missing = required - set(header)
    if missing:
        raise ValueError(f"CSV missing required columns: {missing}. Expected: scene_id,im_id,obj_id,score,R,t,time")
    
    # Build column index map
    col = {name: idx for idx, name in enumerate(header)}
    
    predictions: Dict[str, list] = {}
    skipped = 0
    
    for row_num, row in enumerate(rows[1:], start=2):
        if len(row) < max(col.values()) + 1:
            skipped += 1
            continue
        
        try:
            im_id = row[col["im_id"]].strip()            # frame ID = image ID
            obj_id = int(row[col["obj_id"]])
            
            # Parse R: 9 space-separated floats
            r_str = row[col["r"]].strip()
            r_vals = [float(x) for x in r_str.split()]
            if len(r_vals) != 9:
                raise ValueError(f"Expected 9 R values, got {len(r_vals)}")
            R = np.array(r_vals, dtype=np.float64).reshape(3, 3).tolist()
            
            # Parse t: 3 space-separated floats
            t_str = row[col["t"]].strip()
            t_vals = [float(x) for x in t_str.split()]
            if len(t_vals) != 3:
                raise ValueError(f"Expected 3 t values, got {len(t_vals)}")
            t = t_vals
            
            if im_id not in predictions:
                predictions[im_id] = []
            predictions[im_id].append({
                "obj_id": obj_id,
                "cam_R_m2c": sum(R, []),   # flatten 3×3 → list of 9 floats
                "cam_t_m2c": t,
            })
        except (ValueError, IndexError) as e:
            skipped += 1
            continue
    
    if not predictions:
        raise ValueError(f"No valid prediction rows found (skipped {skipped}). Check CSV format.")
    
    return predictions


# =============================================================================
# MOCK PREDICTION GENERATION
# =============================================================================
def generate_mock_predictions(scene_gt: dict) -> dict:
    """Create dummy predictions by perturbing ground truth poses."""
    predictions = {}
    for f_str, objs in scene_gt.items():
        predictions[f_str] = []
        for obj in objs:
            R_gt = np.array(obj["cam_R_m2c"]).reshape(3, 3)
            t_gt = np.array(obj["cam_t_m2c"])

            # Perturb translation: Gaussian noise σ=15 mm
            t_noise = np.random.normal(0, 15, 3)
            t_pred = t_gt + t_noise

            # Perturb rotation: random axis, small angle ~5-10°
            axis = np.random.randn(3)
            axis /= np.linalg.norm(axis)
            angle_rad = np.random.uniform(0.05, 0.18)  # ~3° to 10°
            # Rodrigues rotation formula via skew-symmetric matrix K
            K = np.array([
                [0, -axis[2], axis[1]],
                [axis[2], 0, -axis[0]],
                [-axis[1], axis[0], 0],
            ])
            R_noise = np.eye(3) + np.sin(angle_rad) * K + (1 - np.cos(angle_rad)) * (K @ K)
            R_pred = R_noise @ R_gt

            predictions[f_str].append({
                "obj_id": obj["obj_id"],
                "cam_t_m2c": t_pred.tolist(),
                "cam_R_m2c": R_pred.flatten().tolist(),
            })
    return predictions


def generate_mock_mask_prediction(gt_mask: np.ndarray, frame_id: int, obj_id: int) -> np.ndarray:
    """Simulate a predicted mask by eroding/dilating the GT mask.
    
    Uses deterministic pseudo-randomness seeded by frame+obj so the same
    (frame, obj) always produces the same 'prediction'.
    """
    if gt_mask is None or gt_mask.sum() == 0:
        return np.zeros((480, 640), dtype=np.uint8)

    rng = np.random.RandomState(frame_id * 1000 + obj_id)
    kernel_size = rng.randint(1, 8)  # erosion kernel 1..7 px
    kernel = np.ones((kernel_size, kernel_size), np.uint8)

    if rng.rand() > 0.5:
        pred = cv2.erode(gt_mask, kernel, iterations=1)
    else:
        pred = cv2.dilate(gt_mask, kernel, iterations=1)

    # Add occasional random shift (0-3 px)
    shift = rng.randint(0, 4)
    if shift > 0:
        dx, dy = rng.randint(-shift, shift + 1, 2)
        M = np.float32([[1, 0, dx], [0, 1, dy]])
        pred = cv2.warpAffine(pred, M, (pred.shape[1], pred.shape[0]))

    return pred


# =============================================================================
# 2D RENDERING: draw bounding boxes & masks onto the RGB image
# =============================================================================
def render_2d_composite(
    frame_id: int,
    scene_gt: dict,
    scene_gt_info: dict,
    predictions: dict,
    show_gt: bool,
    show_pred: bool,
) -> np.ndarray:
    """Return an RGBA numpy array of the RGB image with GT/Pred overlays drawn."""
    rgb_path = os.path.join(RGB_DIR, f"{frame_id:0{_FRAME_PAD}d}.png")
    if not os.path.exists(rgb_path):
        return np.zeros((480, 640, 4), dtype=np.uint8)

    img = cv2.imread(rgb_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    # Convert to RGBA PIL image for alpha-composited drawing
    pil_img = Image.fromarray(img).convert("RGBA")
    overlay = Image.new("RGBA", pil_img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    f_str = str(frame_id)

    def draw_bbox(draw_obj, bbox, colour, label: str):
        """bbox format: [x, y, w, h] (BOP convention)."""
        x, y, w, h = bbox
        r, g, b, a = colour
        # Rectangle outline
        draw_obj.rectangle([x, y, x + w, y + h], outline=(r, g, b, a), width=2)
        # Label text
        tx, ty = x, max(y - 14, 0)
        draw_obj.rectangle([tx, ty, tx + 70, ty + 14], fill=(r, g, b, 180))
        draw_obj.text((tx + 2, ty), label, fill=(255, 255, 255, 255))

    if f_str in scene_gt:
        for obj_idx, gt_obj in enumerate(scene_gt[f_str]):
            gt_info_list = scene_gt_info.get(f_str, [])
            if obj_idx < len(gt_info_list):
                info = gt_info_list[obj_idx]
                if show_gt:
                    draw_bbox(draw, info["bbox_obj"], COLOR_GT, f"GT obj{gt_obj['obj_id']}")
                if show_pred and f_str in predictions and obj_idx < len(predictions[f_str]):
                    # Perturb the bbox to simulate prediction error
                    bx, by, bw, bh = info["bbox_obj"]
                    rng = np.random.RandomState(frame_id * 1000 + obj_idx)
                    bx += rng.randint(-12, 12)
                    by += rng.randint(-12, 12)
                    bw += rng.randint(-8, 8)
                    bh += rng.randint(-8, 8)
                    bw = max(5, bw)
                    bh = max(5, bh)
                    pred_bbox = [max(0, bx), max(0, by), bw, bh]
                    draw_bbox(draw, pred_bbox, COLOR_PRED, f"Pred obj{gt_obj['obj_id']}")

    # Draw mask overlays
    if f_str in scene_gt:
        for obj_idx, gt_obj in enumerate(scene_gt[f_str]):
            obj_id = gt_obj["obj_id"]
            gt_mask = load_mask(frame_id, obj_idx)
            pred_mask = None
            if gt_mask is not None:
                pred_mask = generate_mock_mask_prediction(gt_mask, frame_id, obj_id)

            if show_gt and gt_mask is not None:
                mask_colour = (0, 255, 0, 60)  # semi-transparent green
                mask_rgba = np.zeros((gt_mask.shape[0], gt_mask.shape[1], 4), dtype=np.uint8)
                mask_rgba[gt_mask > 0] = mask_colour
                mask_pil = Image.fromarray(mask_rgba, "RGBA")
                overlay = Image.alpha_composite(overlay, mask_pil)

            if show_pred and pred_mask is not None:
                mask_colour = (255, 60, 60, 60)  # semi-transparent red
                mask_rgba = np.zeros((pred_mask.shape[0], pred_mask.shape[1], 4), dtype=np.uint8)
                mask_rgba[pred_mask > 0] = mask_colour
                mask_pil = Image.fromarray(mask_rgba, "RGBA")
                overlay = Image.alpha_composite(overlay, mask_pil)

            draw = ImageDraw.Draw(overlay)  # reacquire after composite

    result = Image.alpha_composite(pil_img, overlay)
    return np.array(result)


# =============================================================================
# MASK DIFF VISUALISATION — GT as base, errors in red
# =============================================================================
def render_mask_diff(
    frame_id: int,
    scene_gt: dict,
    show_gt: bool,
    show_pred: bool,
) -> np.ndarray:
    """Render a mask comparison image where:
    - Background = black (neither mask)
    - GT mask pixels = green
    - Pixels where GT and predicted masks DISAGREE = red
    - Pixels where BOTH masks agree (1,1) = white
    
    This makes errors immediately visible: any red pixels show where
    the model's predicted mask differs from the ground truth.
    """
    # Default black canvas
    h, w = 480, 640
    result = np.zeros((h, w, 3), dtype=np.uint8)

    gt_mask = load_mask(frame_id, 0)  # obj_seq=0 since this dataset is single-object
    if gt_mask is None:
        return result

    # Generate fake predicted mask (or load real one if available)
    pred_mask = generate_mock_mask_prediction(gt_mask, frame_id, 1)

    if show_gt and gt_mask is not None:
        # GT mask = green base
        result[gt_mask > 0] = (0, 255, 0)
    
    if show_pred and pred_mask is not None:
        # Where BOTH agree (intersection) = white
        both = np.logical_and(gt_mask > 0, pred_mask > 0)
        result[both] = (255, 255, 255)
        # Where PRED says object but GT says background = red (false positive)
        fp = np.logical_and(gt_mask == 0, pred_mask > 0)
        result[fp] = (255, 50, 50)
        # Where GT has object but PRED doesn't = blue (false negative)
        fn = np.logical_and(gt_mask > 0, pred_mask == 0)
        result[fn] = (50, 50, 255)
    
    return result


# =============================================================================
# PLOTLY HELPER — cheap frame marker update (no full rebuild)
# =============================================================================
def _update_plotly_frame_marker(graph_handle, frame_id: int) -> None:
    """Move the dashed yellow vertical line to `frame_id` without rebuilding
    the entire Plotly figure.  This is ~2 ms instead of ~150 ms."""
    fig = graph_handle.figure
    if len(fig.layout.shapes) >= 1:
        fig.layout.shapes[0].x0 = frame_id
        fig.layout.shapes[0].x1 = frame_id
    graph_handle.figure = fig


# =============================================================================
# INTERACTIVE PLOTLY ERROR GRAPHS
# =============================================================================
def build_error_plotly(
    frame_ids: list,
    scene_gt: dict,
    predictions: dict,
    current_frame: Optional[int] = None,
) -> go.Figure:
    """Build a 3-panel Plotly subplot with hover tooltips: rotation error,
    translation error, and mask IOU.  Hovering any data point shows the
    exact frame number and error value.
    """
    # Accumulate per-object errors
    rot_errors = []   # (frame, error, obj_id)
    trans_errors = [] # (frame, error, obj_id)
    iou_errors = []   # (frame, 1-IOU, obj_id)

    for f_id in frame_ids:
        f_str = str(f_id)
        if f_str not in scene_gt or f_str not in predictions:
            continue
        for obj_idx, (gt_obj, pred_obj) in enumerate(zip(scene_gt[f_str], predictions[f_str])):
            R_gt = np.array(gt_obj["cam_R_m2c"]).reshape(3, 3)
            t_gt = np.array(gt_obj["cam_t_m2c"])
            R_pred = np.array(pred_obj["cam_R_m2c"]).reshape(3, 3)
            t_pred = np.array(pred_obj["cam_t_m2c"])
            obj_id = gt_obj["obj_id"]

            rot_errors.append((f_id, rotation_error_deg(R_gt, R_pred), obj_id))
            trans_errors.append((f_id, translation_error_mm(t_gt, t_pred), obj_id))

            gt_mask = load_mask(f_id, obj_idx)
            pred_mask = generate_mock_mask_prediction(
                gt_mask if gt_mask is not None else np.zeros((480, 640), dtype=np.uint8),
                f_id, obj_id,
            )
            if gt_mask is not None:
                iou = compute_iou(gt_mask, pred_mask)
                iou_errors.append((f_id, 1.0 - iou, obj_id))

    def _unpack(data):
        if not data:
            return [], [], []
        xs, ys, ids = zip(*data)
        return list(xs), list(ys), list(ids)

    xs_rot, ys_rot, ids_rot = _unpack(rot_errors)
    xs_trans, ys_trans, ids_trans = _unpack(trans_errors)
    xs_iou, ys_iou, ids_iou = _unpack(iou_errors)

    fig = go.Figure()

    # Panel 1: Rotation Error
    fig.add_trace(go.Scatter(
        x=xs_rot, y=ys_rot, mode="markers+lines",
        marker=dict(size=4, color="#ff9944"), line=dict(width=1, color="#ff9944"),
        name="Rot Err (deg)",
        customdata=list(zip(ids_rot)),
        hovertemplate="Frame %{x}<br>Rot Err: %{y:.2f}°<br>Obj %{customdata[0]}<extra></extra>",
        yaxis="y1",
    ))

    # Panel 2: Translation Error
    fig.add_trace(go.Scatter(
        x=xs_trans, y=ys_trans, mode="markers+lines",
        marker=dict(size=4, color="#44aaff"), line=dict(width=1, color="#44aaff"),
        name="Trans Err (mm)",
        customdata=list(zip(ids_trans)),
        hovertemplate="Frame %{x}<br>Trans Err: %{y:.2f} mm<br>Obj %{customdata[0]}<extra></extra>",
        yaxis="y2",
    ))

    # Panel 3: Mask Error (1 - IOU)
    fig.add_trace(go.Scatter(
        x=xs_iou, y=ys_iou, mode="markers+lines",
        marker=dict(size=4, color="#44ff88"), line=dict(width=1, color="#44ff88"),
        name="Mask Err (1-IOU)",
        customdata=list(zip(ids_iou)),
        hovertemplate="Frame %{x}<br>Mask Err: %{y:.4f}<br>Obj %{customdata[0]}<extra></extra>",
        yaxis="y3",
    ))

    # Current-frame vertical line annotations across all subplots
    shapes = []
    if current_frame is not None:
        shapes.append(dict(
            type="line", x0=current_frame, x1=current_frame,
            y0=0, y1=1, yref="paper",
            line=dict(color="#ffdd00", width=1.5, dash="dash"),
        ))

    # Layout: 3 rows, 1 column, shared x-axis
    fig.update_layout(
        template="plotly_dark",
        height=600,
        margin=dict(l=50, r=20, t=40, b=40),
        hovermode="x unified",
        shapes=shapes,
        grid=dict(rows=3, columns=1, pattern="independent"),
        xaxis3=dict(title="Frame ID"),
        yaxis1=dict(title="Degrees", domain=[0.68, 1.0]),
        yaxis2=dict(title="mm", domain=[0.35, 0.65]),
        yaxis3=dict(title="1 - IOU", domain=[0.0, 0.32]),
    )

    return fig


# =============================================================================
# MAIN DASHBOARD
# =============================================================================
def main():
    print("═" * 60)
    print("  BOP Dataset Visualisation Dashboard — Part 2")
    print("  Dataset: TUD-L  |  Scene: 000001")
    print("═" * 60)

    # --- Load data ---
    scene_camera = load_json("scene_camera.json")
    scene_gt = load_json("scene_gt.json")
    scene_gt_info = load_json("scene_gt_info.json")

    frame_ids = sorted(int(k) for k in scene_camera.keys())
    min_frame, max_frame = frame_ids[0], frame_ids[-1]
    print(f"Loaded {len(frame_ids)} frames (IDs {min_frame}..{max_frame})")

    # --- Generate mock predictions ---
    print("Generating mock predictions (pose + mask)...")
    predictions = generate_mock_predictions(scene_gt)

    # Preload all mask IOU data for the global error graph
    print("Computing mask IOUs for all frames...")
    all_mask_ious = {}
    for f_id in frame_ids:
        f_str = str(f_id)
        if f_str in scene_gt:
            for obj_idx, obj in enumerate(scene_gt[f_str]):
                gt_mask = load_mask(f_id, obj_idx)
                pred_mask = generate_mock_mask_prediction(
                    gt_mask if gt_mask is not None else np.zeros((480, 640), dtype=np.uint8),
                    f_id,
                    obj["obj_id"],
                )
                if gt_mask is not None:
                    all_mask_ious[(f_id, obj["obj_id"])] = compute_iou(gt_mask, pred_mask)

    # --- Start Viser server ---
    server = viser.ViserServer()
    print("\nViser server started → http://localhost:8080\n")

    # Pre-render the Plotly error graph
    error_plotly_fig = build_error_plotly(frame_ids, scene_gt, predictions)

    # Compute where objects are in 3D to center the camera
    all_gt_positions = []
    for f_str in scene_gt:
        for obj in scene_gt[f_str]:
            all_gt_positions.append(obj["cam_t_m2c"])
    if all_gt_positions:
        center = np.mean(all_gt_positions, axis=0)
        # Camera looks at the objects from ~600mm behind and slightly above
        look_at = center  # e.g. [0, 0, 850]
        cam_pos = np.array([look_at[0], look_at[1] + 300.0, look_at[2] - 500.0])
    else:
        look_at = (0.0, 0.0, 0.0)
        cam_pos = (0.0, 300.0, -500.0)

    server.initial_camera.position = np.array(cam_pos, dtype=np.float64)
    server.initial_camera.look_at = np.array(look_at, dtype=np.float64)
    server.initial_camera.far = 8000.0   # far enough to see objects even at 2000mm+
    server.initial_camera.fov = 55.0     # slightly wider field of view

    # --- GUI: left panel controls ---
    with server.gui.add_folder("🎮 Controls"):
        frame_slider = server.gui.add_slider(
            "Frame",
            min=min_frame,
            max=max_frame,
            step=1,
            initial_value=min_frame,
        )
        btn_prev = server.gui.add_button("◀ Prev Frame")
        btn_next = server.gui.add_button("Next Frame ▶")
        show_gt_cb = server.gui.add_checkbox("Show Ground Truth", initial_value=True)
        show_pred_cb = server.gui.add_checkbox("Show Predictions", initial_value=True)

        # Object filter dropdown
        unique_obj_ids = sorted(set(
            obj["obj_id"] for f_str in scene_gt for obj in scene_gt[f_str]
        ))
        obj_id_options = [str(oid) for oid in unique_obj_ids]
        obj_id_options.insert(0, "All")
        obj_filter_dropdown = server.gui.add_dropdown(
            "Object ID Filter",
            options=obj_id_options,
            initial_value="All",
        )
        stats_md = server.gui.add_markdown(
            "*Use slider or buttons to switch frames.  Press **R** in 3D view to reset camera.*"
        )

    # The 2D composite image (rendered each frame change)
    with server.gui.add_folder("📷 2D View (RGB + Boxes + Masks)"):
        composite_2d = render_2d_composite(min_frame, scene_gt, scene_gt_info, predictions, True, True)
        image_gui = server.gui.add_image(
            composite_2d,
            format="png",
        )

    # Mask diff panel — GT/Pred mask comparison
    with server.gui.add_folder("🎭 Mask Diff (GT vs Pred)"):
        mask_diff_img = render_mask_diff(min_frame, scene_gt, True, True)
        mask_diff_gui = server.gui.add_image(
            mask_diff_img,
            format="png",
        )
        server.gui.add_markdown(
            "**Colour Legend:**\n\n"
            "- 🟩 **Green** = GT mask pixels (the true object silhouette)\n"
            "- ⬜ **White** = Both masks agree — GT AND prediction say \"object\"\n"
            "- 🟥 **Red** = False positive — prediction says \"object\" but GT says \"background\"\n"
            "- 🟦 **Blue** = False negative — GT says \"object\" but prediction says \"background\"\n"
            "- ⬛ **Black** = Neither mask has the object"
        )

    # Error graph panel — interactive Plotly with hover tooltips
    with server.gui.add_folder("📈 Error Graphs"):
        graph_gui = server.gui.add_plotly(
            error_plotly_fig,
            config={"displayModeBar": True, "displaylogo": False},
        )

    # --- Upload model data folder ---
    # Persistent extraction directory so RGB/mask files survive after upload
    _persistent_extract_dir = os.path.join(tempfile.gettempdir(), "cnos_uploaded_data")

    with server.gui.add_folder("📤 Upload Model Results"):
        upload_btn = server.gui.add_upload_button(
            "Upload Data Folder (ZIP)",
            mime_type=".zip,application/zip",
        )
        upload_status = server.gui.add_markdown(
            "### How to upload your model's results\n\n"
            "Upload a **.zip file** containing a BOP dataset.  The dashboard will "
            "automatically find the scene folder and 3D models, regardless of nesting.\n\n"
            "**Standard BOP structure:**\n"
            "```\n"
            "tudl/\n"
            "├── models/[_eval]/          (3D CAD models + models_info.json)\n"
            "│   ├── obj_000001.ply\n"
            "│   ├── obj_000002.ply\n"
            "│   └── …\n"
            "├── test/                     (or train/val/onboarding)\n"
            "│   └── 000002/\n"
            "│       ├── rgb/\n"
            "│       ├── depth/\n"
            "│       ├── mask/\n"
            "│       ├── mask_visib/       (optional)\n"
            "│       ├── scene_camera.json\n"
            "│       ├── scene_gt.json\n"
            "│       └── scene_gt_info.json\n"
            "```\n\n"
            "**What happens on upload:**\n"
            "- 3D models replace the current CAD meshes in the 3D view\n"
            "- scene_gt.json replaces the current ground truth data\n"
            "- All views and graphs update automatically"
        )
        predictions_container = [predictions]
        prev_upload_content = [None]

        def check_and_process_upload():
            """Called from the keep-alive polling loop to detect uploads."""
            uf = upload_btn.value
            if uf is None or not uf.content or len(uf.content) == 0:
                return
            content = bytes(uf.content)
            if content == prev_upload_content[0]:
                return
            prev_upload_content[0] = content
            upload_status.content = "**Processing... ⏳**"
            try:
                import shutil
                zf = zipfile.ZipFile(io.BytesIO(content))
                # Extract to a persistent directory
                extract_base = _persistent_extract_dir
                if os.path.exists(extract_base):
                    shutil.rmtree(extract_base, ignore_errors=True)
                os.makedirs(extract_base, exist_ok=True)
                zf.extractall(extract_base)

                # --- Find models/ folder anywhere in the extraction tree ---
                models_dir = None
                for root, dirs, files in os.walk(extract_base):
                    if "models" in dirs:
                        # Look for models/ or models_eval/
                        for cand in dirs:
                            if cand.startswith("models"):
                                models_dir = os.path.join(root, cand)
                                break
                    if models_dir:
                        break

                # --- Find the numeric scene folder (test/000002, train/000001, or top-level) ---
                scene_dir = None
                # First: look for a numeric-named folder at the top level
                for d in sorted(os.listdir(extract_base)):
                    full = os.path.join(extract_base, d)
                    if os.path.isdir(full) and d.isdigit():
                        scene_dir = full
                        break
                # If not found at top level, search inside test/, train/, val/ folders
                if scene_dir is None:
                    for split_name in ("test", "train", "val", "onboarding_static", "onboarding_dynamic"):
                        split_path = os.path.join(extract_base, split_name)
                        if os.path.isdir(split_path):
                            for d in sorted(os.listdir(split_path)):
                                full = os.path.join(split_path, d)
                                if os.path.isdir(full) and d.isdigit():
                                    scene_dir = full
                                    break
                        if scene_dir:
                            break
                # Last resort: walk the whole tree for scene_gt.json
                if scene_dir is None:
                    for root, dirs, files in os.walk(extract_base):
                        if "scene_gt.json" in files:
                            scene_dir = root
                            break
                if scene_dir is None:
                    raise ValueError(
                        "ZIP must contain a numeric scene folder (e.g. '000001/' or 'test/000001/') with scene_gt.json inside"
                    )

                # --- Read JSON files ---
                scene_gt_path = os.path.join(scene_dir, "scene_gt.json")
                if os.path.exists(scene_gt_path):
                    with open(scene_gt_path) as f:
                        new_gt = json.load(f)
                    nonlocal scene_gt
                    scene_gt = new_gt

                # --- Load 3D CAD models ---
                if models_dir and os.path.isdir(models_dir):
                    loaded_count = 0
                    for fname in sorted(os.listdir(models_dir)):
                        if fname.endswith(".ply") and fname.startswith("obj_"):
                            obj_id_str = fname.replace("obj_", "").replace(".ply", "")
                            try:
                                oid = int(obj_id_str)
                                ply_path = os.path.join(models_dir, fname)
                                mesh = trimesh.load(ply_path)
                                _mesh_cache[oid] = mesh
                                loaded_count += 1
                                print(f"  Loaded uploaded mesh obj_{oid:06d}: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")
                            except (ValueError, Exception) as exc:
                                print(f"  Skipped {fname}: {exc}")
                    if loaded_count > 0:
                        print(f"Replaced {loaded_count} CAD models from upload.")

                # --- Re-point all data directories to the uploaded scene ---
                global DATA_DIR, RGB_DIR, MASK_DIR, MASK_VISIB_DIR, _FRAME_PAD
                DATA_DIR = scene_dir
                RGB_DIR = os.path.join(DATA_DIR, "rgb")
                MASK_DIR = os.path.join(DATA_DIR, "mask")
                MASK_VISIB_DIR = os.path.join(DATA_DIR, "mask_visib")
                _FRAME_PAD = _detect_frame_padding(MASK_DIR)
                print(f"  Detected frame padding: {_FRAME_PAD} digits")
                # Re-build frame IDs
                nonlocal frame_ids, min_frame, max_frame
                frame_ids = sorted(int(k) for k in scene_gt.keys())
                min_frame, max_frame = frame_ids[0], frame_ids[-1]

                # Generate new predictions from uploaded GT
                nonlocal predictions
                predictions = generate_mock_predictions(scene_gt)

                # Recompute IOUs
                nonlocal all_mask_ious
                all_mask_ious = {}
                for f_id in frame_ids:
                    f_str = str(f_id)
                    if f_str in scene_gt:
                        for obj_idx, obj in enumerate(scene_gt[f_str]):
                            gt_mask = load_mask(f_id, obj_idx)
                            pred_mask = generate_mock_mask_prediction(
                                gt_mask if gt_mask is not None else np.zeros((480, 640), dtype=np.uint8),
                                f_id, obj["obj_id"],
                            )
                            if gt_mask is not None:
                                all_mask_ious[(f_id, obj["obj_id"])] = compute_iou(gt_mask, pred_mask)

                # Update slider range
                frame_slider.max = max_frame
                frame_slider.min = min_frame
                frame_slider.value = min_frame

                predictions_container[0] = predictions

                # Also update scene_camera and scene_gt_info if provided
                scene_camera_path = os.path.join(scene_dir, "scene_camera.json")
                if os.path.exists(scene_camera_path):
                    with open(scene_camera_path) as f:
                        nonlocal scene_camera
                        scene_camera = json.load(f)
                scene_gt_info_path = os.path.join(scene_dir, "scene_gt_info.json")
                if os.path.exists(scene_gt_info_path):
                    with open(scene_gt_info_path) as f:
                        nonlocal scene_gt_info
                        scene_gt_info = json.load(f)

                n_frames = len(frame_ids)
                upload_status.content = (
                    f"**✅ Uploaded!** {n_frames} frames loaded.\n\n"
                    f"All views and graphs updated."
                )
                update_all(int(frame_slider.value))
            except Exception as e:
                upload_status.content = f"**❌ Error:** {str(e)[:300]}"

    # 3D scene setup
    server.scene.add_icosphere(
        "/origin",
        radius=8.0,
        position=(0, 0, 0),
        color=(150, 150, 150),
    )

    # Store handles for 3D scene objects so we can clear them
    scene_handles = []

    # Preload all CAD meshes referenced in the dataset at startup
    print("Loading 3D CAD models...")
    all_obj_ids = set()
    for f_str in scene_gt:
        for obj in scene_gt[f_str]:
            all_obj_ids.add(obj["obj_id"])
    for oid in sorted(all_obj_ids):
        get_mesh(oid)  # triggers cache loading
    print(f"Cached {len(_mesh_cache)} meshes.\n")

    def draw_3d_objects(frame_id: int):
        """Draw/update 3D CAD meshes at GT (green) and Pred (red) poses."""
        nonlocal scene_handles
        for h in scene_handles:
            h.remove()
        scene_handles.clear()

        f_str = str(frame_id)
        if f_str not in scene_gt:
            return

        # Camera at origin with coordinate axes
        cam_handle = server.scene.add_frame(
            "/camera_origin",
            show_axes=True,
            axes_length=50.0,
            axes_radius=3.0,
            position=(0, 0, 0),
        )
        scene_handles.append(cam_handle)

        for obj_idx, gt_obj in enumerate(scene_gt[f_str]):
            obj_id = gt_obj["obj_id"]
            mesh = _mesh_cache.get(obj_id)

            # ---- GROUND TRUTH (solid green) ----
            if show_gt_cb.value:
                R_gt = np.array(gt_obj["cam_R_m2c"]).reshape(3, 3)
                t_gt = np.array(gt_obj["cam_t_m2c"])
                wxyz_gt = matrix_to_quat_wxyz(R_gt)

                if mesh is not None:
                    # Render the CAD model as a solid green mesh
                    h_mesh = server.scene.add_mesh_simple(
                        f"/gt_mesh_{obj_id}",
                        vertices=np.asarray(mesh.vertices, dtype=np.float32),
                        faces=np.asarray(mesh.faces, dtype=np.uint32),
                        color=(0, 180, 0),        # solid green fill
                        wireframe=False,
                        flat_shading=False,
                        position=t_gt,
                        wxyz=wxyz_gt,
                    )
                    scene_handles.append(h_mesh)
                else:
                    h_box = server.scene.add_box(
                        f"/gt_box_{obj_id}",
                        dimensions=(30, 30, 30),
                        position=t_gt,
                        wxyz=wxyz_gt,
                        color=(0, 200, 0),
                    )
                    scene_handles.append(h_box)
                # Coordinate frame for orientation reference
                h_frame = server.scene.add_frame(
                    f"/gt_frame_{obj_id}",
                    show_axes=True,
                    axes_length=30.0,
                    axes_radius=1.5,
                    position=t_gt,
                    wxyz=wxyz_gt,
                )
                scene_handles.append(h_frame)

            # ---- PREDICTION (solid red) ----
            if show_pred_cb.value and f_str in predictions and obj_idx < len(predictions[f_str]):
                pred_obj = predictions[f_str][obj_idx]
                R_pred = np.array(pred_obj["cam_R_m2c"]).reshape(3, 3)
                t_pred = np.array(pred_obj["cam_t_m2c"])
                wxyz_pred = matrix_to_quat_wxyz(R_pred)

                if mesh is not None:
                    # Same CAD model, placed at the predicted pose — solid red
                    h_mesh = server.scene.add_mesh_simple(
                        f"/pred_mesh_{obj_id}",
                        vertices=np.asarray(mesh.vertices, dtype=np.float32),
                        faces=np.asarray(mesh.faces, dtype=np.uint32),
                        color=(180, 20, 20),      # solid red fill
                        wireframe=False,
                        flat_shading=False,
                        position=t_pred,
                        wxyz=wxyz_pred,
                    )
                    scene_handles.append(h_mesh)
                else:
                    h_box = server.scene.add_box(
                        f"/pred_box_{obj_id}",
                        dimensions=(30, 30, 30),
                        position=t_pred,
                        wxyz=wxyz_pred,
                        color=(200, 40, 40),
                    )
                    scene_handles.append(h_box)
                h_frame = server.scene.add_frame(
                    f"/pred_frame_{obj_id}",
                    show_axes=True,
                    axes_length=30.0,
                    axes_radius=1.5,
                    position=t_pred,
                    wxyz=wxyz_pred,
                )
                scene_handles.append(h_frame)

    def update_all(frame_id: int):
        """Refresh 2D composite, 3D scene, error graph, and stats text.
        
        Uses ThreadPoolExecutor to render the 2D composite and mask diff
        in parallel, and only updates the yellow frame marker in the
        already-constructed Plotly figure (cheap ~2ms operation).
        """
        # Render images in parallel using thread pool
        with ThreadPoolExecutor(max_workers=2) as pool:
            fut_2d = pool.submit(
                render_2d_composite,
                frame_id, scene_gt, scene_gt_info, predictions,
                show_gt_cb.value, show_pred_cb.value,
            )
            fut_mask = pool.submit(
                render_mask_diff,
                frame_id, scene_gt, True, True,
            )
            comp = fut_2d.result()
            md_img = fut_mask.result()

        image_gui.image = comp
        mask_diff_gui.image = md_img

        # 3D scene
        draw_3d_objects(frame_id)

        # Update only the yellow marker line in the Plotly graph (cheap)
        _update_plotly_frame_marker(graph_gui, frame_id)

        # Stats markdown
        f_str = str(frame_id)
        md = f"### Frame {frame_id}\n"
        if f_str in scene_gt and f_str in predictions:
            for obj_idx, (gt_obj, pred_obj) in enumerate(zip(scene_gt[f_str], predictions[f_str])):
                R_gt = np.array(gt_obj["cam_R_m2c"]).reshape(3, 3)
                t_gt = np.array(gt_obj["cam_t_m2c"])
                R_pred = np.array(pred_obj["cam_R_m2c"]).reshape(3, 3)
                t_pred = np.array(pred_obj["cam_t_m2c"])
                obj_id = gt_obj["obj_id"]
                r_err = rotation_error_deg(R_gt, R_pred)
                t_err = translation_error_mm(t_gt, t_pred)
                iou_val = all_mask_ious.get((frame_id, obj_id), None)
                md += f"**Obj {obj_id}**\n"
                md += f"- Rot Err: `{r_err:.2f}°`\n"
                md += f"- Trans Err: `{t_err:.2f} mm`\n"
                if iou_val is not None:
                    md += f"- Mask IOU: `{iou_val:.4f}`\n"
                md += "\n"
        stats_md.content = md

    # --- Event callbacks ---
    @frame_slider.on_update
    def _(_):
        update_all(int(frame_slider.value))

    @btn_prev.on_click
    def _(_):
        new_val = max(min_frame, int(frame_slider.value) - 1)
        frame_slider.value = new_val

    @btn_next.on_click
    def _(_):
        new_val = min(max_frame, int(frame_slider.value) + 1)
        frame_slider.value = new_val

    @show_gt_cb.on_update
    def _(_):
        update_all(int(frame_slider.value))

    @show_pred_cb.on_update
    def _(_):
        update_all(int(frame_slider.value))

    @obj_filter_dropdown.on_update
    def _(_):
        update_all(int(frame_slider.value))

    # --- Initial draw ---
    update_all(min_frame)

    print("Dashboard ready! Use slider, buttons, or ← → arrow keys to navigate.\n")
    print("  Green  = Ground Truth     Red = Prediction\n")
    print("Press Ctrl+C to stop.")
    print("Waiting for user uploads or frame changes.\n")

    # --- Keep-alive + upload polling loop ---
    try:
        while True:
            time.sleep(0.3)
            check_and_process_upload()
            # Update the predictions reference that update_all uses
            predictions = predictions_container[0]
    except KeyboardInterrupt:
        print("\nShutting down.")


if __name__ == "__main__":
    main()